//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_log
    {
        public int Log_ID { get; set; }
        public Nullable<int> Sotrudnik_ID { get; set; }
        public Nullable<int> Point_ID { get; set; }
        public Nullable<int> Card_Number { get; set; }
        public Nullable<int> Direction_ID { get; set; }
        public Nullable<System.DateTime> Access_Time { get; set; }
        public Nullable<int> Access_Result_id { get; set; }
        public string Temperature { get; set; }
        public string Session_Device { get; set; }
    
        public virtual Access_points Access_points { get; set; }
        public virtual Access_results Access_results { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual Sotudniki Sotudniki { get; set; }
    }
}
