//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_point_type
    {
        public Access_point_type()
        {
            this.Access_points = new HashSet<Access_points>();
        }
    
        public int Type_id { get; set; }
        public string Type_name { get; set; }
    
        public virtual ICollection<Access_points> Access_points { get; set; }
    }
}
