//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access_points
    {
        public Access_points()
        {
            this.Access_log = new HashSet<Access_log>();
        }
    
        public int Point_ID { get; set; }
        public string Point_Name { get; set; }
        public Nullable<int> Point_Type_id { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Access_log> Access_log { get; set; }
        public virtual Access_point_type Access_point_type { get; set; }
    }
}
