//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DEMKA_GERBER : DbContext
    {
        public DEMKA_GERBER()
            : base("name=DEMKA_GERBER")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Access_level_type> Access_level_type { get; set; }
        public DbSet<Access_log> Access_log { get; set; }
        public DbSet<Access_point_type> Access_point_type { get; set; }
        public DbSet<Access_points> Access_points { get; set; }
        public DbSet<Access_results> Access_results { get; set; }
        public DbSet<Direction> Direction { get; set; }
        public DbSet<Edeniza_Izmerenia> Edeniza_Izmerenia { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<Equipment_type> Equipment_type { get; set; }
        public DbSet<Family_status> Family_status { get; set; }
        public DbSet<Gender> Gender { get; set; }
        public DbSet<Material_types> Material_types { get; set; }
        public DbSet<Materials> Materials { get; set; }
        public DbSet<Oblast> Oblast { get; set; }
        public DbSet<Partner_type> Partner_type { get; set; }
        public DbSet<Partners> Partners { get; set; }
        public DbSet<Postavshik> Postavshik { get; set; }
        public DbSet<Postavshik_type> Postavshik_type { get; set; }
        public DbSet<Product_request> Product_request { get; set; }
        public DbSet<Product_types> Product_types { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<Qualification_Status> Qualification_Status { get; set; }
        public DbSet<Request_status> Request_status { get; set; }
        public DbSet<Sale_place> Sale_place { get; set; }
        public DbSet<Sotrudnik_qualification> Sotrudnik_qualification { get; set; }
        public DbSet<Sotrudnik_roles> Sotrudnik_roles { get; set; }
        public DbSet<Sotudniki> Sotudniki { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Zdorovie> Zdorovie { get; set; }
    }
}
