//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edeniza_Izmerenia
    {
        public Edeniza_Izmerenia()
        {
            this.Materials = new HashSet<Materials>();
            this.Products = new HashSet<Products>();
        }
    
        public int Edeniza_id { get; set; }
        public string edeniza_name { get; set; }
    
        public virtual ICollection<Materials> Materials { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
