//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.Sotrudnik_qualification = new HashSet<Sotrudnik_qualification>();
        }
    
        public int Equipment_ID { get; set; }
        public string Equipment_Name { get; set; }
        public Nullable<int> Equipment_Type_id { get; set; }
        public string Workshop_Number { get; set; }
    
        public virtual Equipment_type Equipment_type { get; set; }
        public virtual ICollection<Sotrudnik_qualification> Sotrudnik_qualification { get; set; }
    }
}
