//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family_status
    {
        public Family_status()
        {
            this.Sotudniki = new HashSet<Sotudniki>();
        }
    
        public int Status_Id { get; set; }
        public string Status_Name { get; set; }
    
        public virtual ICollection<Sotudniki> Sotudniki { get; set; }
    }
}
