//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material_types
    {
        public Material_types()
        {
            this.Materials = new HashSet<Materials>();
        }
    
        public int Material_type_id { get; set; }
        public string Material_type_name { get; set; }
        public Nullable<double> Material_BRAK_Procent { get; set; }
    
        public virtual ICollection<Materials> Materials { get; set; }
    }
}
