//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public Materials()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int Material_id { get; set; }
        public string Material_name { get; set; }
        public Nullable<int> Material_type_id { get; set; }
        public Nullable<int> Postavshik_id { get; set; }
        public Nullable<int> Kolichestvo { get; set; }
        public Nullable<int> Edeniza_izmerenya_Id { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Price { get; set; }
        public Nullable<double> Kolichestvo_On_Sklad { get; set; }
        public Nullable<double> Min_ammount { get; set; }
    
        public virtual Edeniza_Izmerenia Edeniza_Izmerenia { get; set; }
        public virtual Material_types Material_types { get; set; }
        public virtual Postavshik Postavshik { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
