//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oblast
    {
        public Oblast()
        {
            this.Partners = new HashSet<Partners>();
        }
    
        public int Oblast_ID { get; set; }
        public string Oblast_Name { get; set; }
    
        public virtual ICollection<Partners> Partners { get; set; }
    }
}
