//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public Partners()
        {
            this.Product_request = new HashSet<Product_request>();
        }
    
        public int Partner_ID { get; set; }
        public string Partner_Name { get; set; }
        public Nullable<int> Partner_Type_id { get; set; }
        public string Partner_dir_familiya { get; set; }
        public string Partner_dir_name { get; set; }
        public string Partner_dir_otch { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public Nullable<double> Post_Index { get; set; }
        public Nullable<int> Oblast_ID { get; set; }
        public string City { get; set; }
        public string Adress { get; set; }
        public Nullable<double> INN { get; set; }
        public Nullable<double> Rating { get; set; }
        public string logotype { get; set; }
        public Nullable<int> Sale_place_id { get; set; }
    
        public virtual Oblast Oblast { get; set; }
        public virtual Partner_type Partner_type { get; set; }
        public virtual Sale_place Sale_place { get; set; }
        public virtual ICollection<Product_request> Product_request { get; set; }
    }
}
