//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavshik
    {
        public Postavshik()
        {
            this.Materials = new HashSet<Materials>();
        }
    
        public int Postavshik_id { get; set; }
        public string Postavshik_name { get; set; }
        public Nullable<int> Postavshik_type_Id { get; set; }
        public Nullable<double> INN { get; set; }
    
        public virtual ICollection<Materials> Materials { get; set; }
        public virtual Postavshik_type Postavshik_type { get; set; }
    }
}
