//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavshik_type
    {
        public Postavshik_type()
        {
            this.Postavshik = new HashSet<Postavshik>();
        }
    
        public int Type_id { get; set; }
        public string Type_Name { get; set; }
    
        public virtual ICollection<Postavshik> Postavshik { get; set; }
    }
}
