//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Product_request = new HashSet<Product_request>();
        }
    
        public int Product_id { get; set; }
        public string Prouct_name { get; set; }
        public Nullable<int> Product_TypeID { get; set; }
        public Nullable<double> Product_Article { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public Nullable<double> Product_min_price { get; set; }
        public string Razmer { get; set; }
        public Nullable<double> Weight_without_upakovka { get; set; }
        public Nullable<double> Weight_with_upakovka { get; set; }
        public Nullable<int> Edeniza_izm_id { get; set; }
        public string Aprovement_Certificate { get; set; }
        public string Standart_number { get; set; }
        public Nullable<System.DateTime> Date_of_made { get; set; }
        public Nullable<double> cost_price { get; set; }
        public string Zeh_number { get; set; }
        public Nullable<double> Kolichestvo_chelovek { get; set; }
        public Nullable<int> Materials_id { get; set; }
    
        public virtual Edeniza_Izmerenia Edeniza_Izmerenia { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual ICollection<Product_request> Product_request { get; set; }
        public virtual Product_types Product_types { get; set; }
    }
}
