//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_types
    {
        public Product_types()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int Produtc_Type_id { get; set; }
        public string Product_Type_Name { get; set; }
        public Nullable<double> Product_Type_Koeficient { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
