//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_request
    {
        public int Request_Id { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> Partner_id { get; set; }
        public Nullable<double> Request_Ammount { get; set; }
        public Nullable<System.DateTime> Date_of_request { get; set; }
        public Nullable<int> Request_status_id { get; set; }
        public Nullable<decimal> Price_For_edeniza { get; set; }
        public Nullable<double> Srok_Izgotovlenia { get; set; }
        public Nullable<decimal> PredOplata_ammount { get; set; }
        public Nullable<System.DateTime> Date_of_deliver { get; set; }
        public Nullable<int> Sotrudnik_prinyal_id { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
        public virtual Request_status Request_status { get; set; }
        public virtual Sotudniki Sotudniki { get; set; }
    }
}
