//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification_Status
    {
        public Qualification_Status()
        {
            this.Sotrudnik_qualification = new HashSet<Sotrudnik_qualification>();
        }
    
        public int Qualification_Status1 { get; set; }
        public string Status_name { get; set; }
    
        public virtual ICollection<Sotrudnik_qualification> Sotrudnik_qualification { get; set; }
    }
}
