//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request_status
    {
        public Request_status()
        {
            this.Product_request = new HashSet<Product_request>();
        }
    
        public int Status_id { get; set; }
        public string Status_name { get; set; }
    
        public virtual ICollection<Product_request> Product_request { get; set; }
    }
}
