//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_place
    {
        public Sale_place()
        {
            this.Partners = new HashSet<Partners>();
        }
    
        public int Place_id { get; set; }
        public string Place_name { get; set; }
    
        public virtual ICollection<Partners> Partners { get; set; }
    }
}
