//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik_qualification
    {
        public int Qualification_ID { get; set; }
        public Nullable<int> Sotrudnik_ID { get; set; }
        public Nullable<int> Equipment_ID { get; set; }
        public Nullable<int> Access_Level_Type_id { get; set; }
        public string Certificate_Number { get; set; }
        public Nullable<System.DateTime> Issue_Date { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<int> Sotrudnik_Utverdil_id { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<System.DateTime> Medical_Check_Date { get; set; }
        public string Notes { get; set; }
    
        public virtual Access_level_type Access_level_type { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Qualification_Status Qualification_Status { get; set; }
        public virtual Sotudniki Sotudniki { get; set; }
        public virtual Sotudniki Sotudniki1 { get; set; }
    }
}
