//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMKA_GERBER_1.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotudniki
    {
        public Sotudniki()
        {
            this.Access_log = new HashSet<Access_log>();
            this.Product_request = new HashSet<Product_request>();
            this.Sotrudnik_qualification = new HashSet<Sotrudnik_qualification>();
            this.Sotrudnik_qualification1 = new HashSet<Sotrudnik_qualification>();
        }
    
        public int Sotrudnik_id { get; set; }
        public string Sotrudnik_Familiya { get; set; }
        public string Sotrudnik_name { get; set; }
        public string Sotrudnik_Otch { get; set; }
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        public Nullable<int> Sotrudnik_role_id { get; set; }
        public string Login { get; set; }
        public string password { get; set; }
        public Nullable<double> Pasport { get; set; }
        public Nullable<double> Bank_card { get; set; }
        public Nullable<int> Family_status_Id { get; set; }
        public Nullable<int> Zdorovie_Id { get; set; }
        public Nullable<int> Gender_id { get; set; }
    
        public virtual ICollection<Access_log> Access_log { get; set; }
        public virtual Family_status Family_status { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<Product_request> Product_request { get; set; }
        public virtual ICollection<Sotrudnik_qualification> Sotrudnik_qualification { get; set; }
        public virtual ICollection<Sotrudnik_qualification> Sotrudnik_qualification1 { get; set; }
        public virtual Sotrudnik_roles Sotrudnik_roles { get; set; }
        public virtual Zdorovie Zdorovie { get; set; }
    }
}
